[package]
org = "dilhasha"
name = "sample"
version = "0.1.0"
distribution = "2201.9.3"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../resource-reader/app/build/libs/app.jar"